---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
- name: Vulnerabilities
  image: code.icb4dc0.de/inetmock/ci-images/go-ci
  commands:
    - go run github.com/magefile/mage -d build -w . generate
    - go run golang.org/x/vuln/cmd/govulncheck@latest -tags "$${GO_BUILD_TAGS}" ./...
  environment:
    GO_BUILD_TAGS: sudo,integration

- name: Lint
  image: code.icb4dc0.de/inetmock/ci-images/go-ci
  commands:
    - go run github.com/magefile/mage -d build -w . lint

- name: Tests
  image: code.icb4dc0.de/inetmock/ci-images/go-ci
  privileged: true
  network_mode: host
  commands:
    - mount -t debugfs debugfs /sys/kernel/debug
    - go run github.com/magefile/mage -d build -w . testAll
    - go run github.com/magefile/mage -d build -w . integrationTests
  environment:
    KO_DOCKER_REPO: inetmock.icb4dc0.de/inetmock
  depends_on:
    - Vulnerabilities
    - Lint

- name: Release
  image: code.icb4dc0.de/inetmock/ci-images/go-ci
  when:
    event:
      - tag
  depends_on:
    - Tests
  commands:
    - goreleaser release --rm-dist

---
kind: pipeline
type: docker
name: housekeeping

trigger:
  event:
  - cron
  cron:
    - housekeeping

steps:
  - name: Renovate
    image: docker.io/renovate/renovate
    commands:
      - "renovate inetmock/inetmock"
    environment:
      RENOVATE_TOKEN:
        from_secret: gitea_token
      GITHUB_COM_TOKEN:
        from_secret: github_token
      RENOVATE_PLATFORM: gitea
      RENOVATE_AUTODISCOVER: "false"
      RENOVATE_ENDPOINT: https://code.icb4dc0.de/api/v1
      LOG_LEVEL: info
