---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  branch: 
  - main
  event:
    - push
    - pull_request
    - tag

steps:
  - name: Vulnerabilities
    image: code.icb4dc0.de/inetmock/ci-images/go-ci
    commands:
      - go run github.com/magefile/mage -d build -w . generate
      - go run golang.org/x/vuln/cmd/govulncheck@latest -tags "$${GO_BUILD_TAGS}" ./...
    environment:
      GO_BUILD_TAGS: sudo,integration
    volumes:
      - name: go-cache
        path: /go

  - name: Lint
    image: code.icb4dc0.de/inetmock/ci-images/go-ci
    commands:
      - go run github.com/magefile/mage -d build -w . lint
    volumes:
      - name: go-cache
        path: /go

  - name: Tests
    image: code.icb4dc0.de/inetmock/ci-images/go-ci
    privileged: true
    network_mode: host
    commands:
      - mount -t debugfs debugfs /sys/kernel/debug
      - go run github.com/magefile/mage -d build -w . testAll
      - go run github.com/magefile/mage -d build -w . integrationTests
    environment:
      DOCKER_HOST: tcp://localhost:2375
      TC_DISABLE_REAPER: 'true'
    volumes:
      - name: go-cache
        path: /go

  - name: Release
    image: code.icb4dc0.de/inetmock/ci-images/go-ci
    when:
      event:
        - tag
    volumes:
      - name: go-cache
        path: /go
    commands:
      - goreleaser release --rm-dist

volumes:
  - name: go-cache
    temp: { }

---
kind: pipeline
type: docker
name: housekeeping

trigger:
  event:
    - cron
  cron:
    - housekeeping

steps:
  - name: Renovate
    image: code.icb4dc0.de/prskr/ci-images/renovate:latest
    commands:
      - "renovate inetmock/inetmock"
    environment:
      RENOVATE_TOKEN:
        from_secret: gitea_token
      GITHUB_COM_TOKEN:
        from_secret: github_token
      RENOVATE_PLATFORM: gitea
      RENOVATE_AUTODISCOVER: "false"
      RENOVATE_ENDPOINT: https://code.icb4dc0.de/api/v1
      LOG_LEVEL: info
