linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: gitlab.com/inetmock/inetmock
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
    disabled-checks:
      - ifElseChain
      - octalLiteral
      - wrapperFunc
    settings:
      hugeParam:
        sizeThreshold: 200
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: gitlab.com/inetmock/inetmock
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks:
          - argument
          - case
          - condition
          - return
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  importas:
    no-unaliased: true
    alias:
      - pkg: gitlab.com/inetmock/inetmock/pkg/(audit|rpc)/(v[\w\d]+)
        alias: $1$2
      - pkg: github.com/miekg/dns
        alias: mdns
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofumpt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - promlinter
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace

    #- unused

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - govet

run:
  build-tags:
    - sudo
  skip-dirs:
    - internal/mock
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*.mock.\\.go$"

service:
  golangci-lint-version: 1.42.x # use the fixed version to not introduce new linters unexpectedly
