builds:
  - id: "inetmock"
    binary: inetmock
    main: ./cmd/inetmock/
    flags:
      - -trimpath
      - -a
      - -installsuffix=cgo
    ldflags:
      - -w -s
      - -linkmode=external
      - -extldflags -static
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: "imctl"
    binary: imctl
    main: ./cmd/imctl/
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - id: inetmock
    builds:
      - inetmock
    name_template: "{{ .ProjectName }}_server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
    wrap_in_directory: true
    files:
      - config.yaml
      - "*.so"
  - id: imctl
    builds:
      - imctl
    name_template: "{{ .ProjectName }}_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
    wrap_in_directory: true
    files: [ ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  gitea:
    owner: inetmock
    name: inetmock
