---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: code.icb4dc0.de/inetmock/ci-images/go-ci
    tag: latest
    username: ((gitea-credentials.user))
    password: ((gitea-credentials.token))

inputs:
- name: repo
  path: .

container_limits:
  cpu: 1500
  memory: 1258291200 # 1200MB

run:
  path: sh
  args:
  - -ce
  - |
    mount -t debugfs debugfs /sys/kernel/debug
    go run github.com/magefile/mage testAll
