---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: code.icb4dc0.de/inetmock/ci-images/go-ci
    tag: latest
    username: ((gitea-credentials.user))
    password: ((gitea-credentials.token))

inputs:
  - name: repo
    path: .

params:
  GITEA_TOKEN: ((gitea-credentials.token))

run:
  path: bash
  args:
    - -ce
    - |
      if [[ "$(git tag --contains $(git rev-parse --short HEAD))" != "" ]];
      then
        goreleaser release --rm-dist
      else
        goreleaser release --snapshot --rm-dist
      fi
