---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: code.icb4dc0.de/inetmock/ci-images/go-ci
    tag: latest
    username: ((gitea-credentials.user))
    password: ((gitea-credentials.token))

inputs:
  - name: repo
    path: .

params:
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  GITEA_TOKEN: ((gitea-credentials.token))

run:
  path: sh
  args:
    - -ce
    - |
      go run github.com/magefile/mage integrationTests
