---
resources:
  - name: inetmock.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/inetmock/inetmock.git
      branch: ((branch))

  - name: templates.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/prskr/pipeline-templates.git

jobs:
- name: validate
  plan:
    - in_parallel:
      - get: inetmock.git
        trigger: true
      - get: templates.git
    - load_var: git_ref
      format: trim
      file: inetmock.git/.git/ref
    # run lint step here to generate all files e.g. eBPF object files
    - task: generate
      file: inetmock.git/.concourse/tasks/generate.yml
      input_mapping: {repo: inetmock.git}
    - in_parallel:
      - task: lint
        file: inetmock.git/.concourse/tasks/lint.yml
        tags: [ linux,vm ]
        input_mapping: { repo: generated-sources }
        on_success:
          task: report-success
          file: templates.git/tasks/gitea-status-v2.yml
          vars:
            project_path: inetmock/inetmock
            git_ref: ((.:git_ref))
            context: concourse-ci/lint/golangci-lint
            description: Lint Go files
            state: success
        on_failure:
          task: report-failure
          file: templates.git/tasks/gitea-status-v2.yml
          vars:
            project_path: inetmock/inetmock
            git_ref: ((.:git_ref))
            context: concourse-ci/lint/golangci-lint
            description: Lint Go files
            state: failure
      - task: vulnerabilities
        file: templates.git/tasks/go-vulnerabilities.yml
        tags: [ linux,vm ]
        params:
          GO_BUILD_TAGS: sudo,integration
        input_mapping: { repo: generated-sources }
        on_success:
          task: report-success
          file: templates.git/tasks/gitea-status-v2.yml
          vars:
            project_path: inetmock/inetmock
            git_ref: ((.:git_ref))
            context: concourse-ci/lint/vulnerabilities
            description: Check for vulnerabilities
            state: success
        on_failure:
          task: report-failure
          file: templates.git/tasks/gitea-status-v2.yml
          vars:
            project_path: inetmock/inetmock
            git_ref: ((.:git_ref))
            context: concourse-ci/lint/vulnerabilities
            description: Check for vulnerabilities
            state: failure
      - task: snapshot-release
        file: templates.git/tasks/goreleaser.yml
        input_mapping: {repo: generated-sources}
      - task: ko
        file: templates.git/tasks/ko.yml
        input_mapping: { repo: generated-sources }
        vars:
          docker_repo: code.icb4dc0.de/inetmock
          build_package: ./cmd/inetmock
          push_image: 'false'
          git_ref: ((.:git_ref))

- name: test
  plan:
  - in_parallel:
      - get: inetmock.git
        trigger: true
      - get: templates.git
  - load_var: git_ref
    format: trim
    file: inetmock.git/.git/ref
  - in_parallel:
    - task: unit
      tags: [linux,vm]
      privileged: true
      file: inetmock.git/.concourse/tasks/go-test.yml
      input_mapping: {repo: inetmock.git}
      on_success:
        task: report-success
        file: templates.git/tasks/gitea-status-v2.yml
        vars:
          project_path: inetmock/inetmock
          git_ref: ((.:git_ref))
          context: concourse-ci/test/unit
          description: Run unit tests
          state: success
      on_failure:
        task: report-failure
        file: templates.git/tasks/gitea-status-v2.yml
        vars:
          project_path: inetmock/inetmock
          git_ref: ((.:git_ref))
          context: concourse-ci/test/unit
          description: Run unit tests
          state: failure
    - task: integration
      tags: [linux,vm]
      privileged: true
      file: inetmock.git/.concourse/tasks/integration-test.yml
      input_mapping: {repo: inetmock.git}
      on_success:
        task: report-success
        file: templates.git/tasks/gitea-status-v2.yml
        vars:
          project_path: inetmock/inetmock
          git_ref: ((.:git_ref))
          context: concourse-ci/test/integration
          description: Run integration tests
          state: success
      on_failure:
        task: report-failure
        file: templates.git/tasks/gitea-status-v2.yml
        vars:
          project_path: inetmock/inetmock
          git_ref: ((.:git_ref))
          context: concourse-ci/test/integration
          description: Run integration tests
          state: failure
