---
resources:
  - name: daily
    type: time
    source:
      interval: 24h
  - name: inetmock.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/inetmock/inetmock.git
  - name: templates.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/prskr/pipeline-templates.git

jobs:
  - name: renovate
    plan:
      - in_parallel:
        - get: inetmock.git
          trigger: true
        - get: templates.git
        - get: daily
          trigger: true
      - task: renovate
        tags: [ linux,vm ]
        file: templates.git/tasks/renovate.yml
        input_mapping: { repo: inetmock.git }
        vars:
          project_path: inetmock/inetmock