---
resources:
- name: inetmock.git
  type: git
  icon: github
  source:
    uri: https://code.icb4dc0.de/inetmock/inetmock.git
    branch: ((branch))

jobs:
- name: test
  plan:
  - get: inetmock.git
    trigger: true
  - task: lint
    file: inetmock.git/.concourse/tasks/lint.yml
    input_mapping: {repo: inetmock.git}
  - task: unit
    tags: [linux,vm]
    privileged: true
    file: inetmock.git/.concourse/tasks/go-test.yml
    input_mapping: {repo: inetmock.git}
