---
resources:
  - name: inetmock.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/inetmock/inetmock.git
      fetch_tags: true
      tag_filter: "v*"

  - name: templates.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/prskr/pipeline-templates.git

jobs:
  - name: release
    plan:
      - in_parallel:
          - get: inetmock.git
            trigger: true
          - get: templates.git
      - in_parallel:
          - task: lint
            file: inetmock.git/.concourse/tasks/lint.yml
            tags: [ linux,vm ]
            input_mapping: { repo: inetmock.git }
          - task: unit
            tags: [ linux,vm ]
            privileged: true
            file: inetmock.git/.concourse/tasks/go-test.yml
            input_mapping: { repo: inetmock.git }
          - task: integration
            privileged: true
            file: inetmock.git/.concourse/tasks/integration-test.yml
            input_mapping: { repo: inetmock.git }
      - in_parallel:
          - task: goreleaser
            file: templates.git/tasks/goreleaser.yml
            input_mapping: { repo: inetmock.git }
          - task: ko
            file: templates.git/tasks/goreleaser.yml
            input_mapping: { repo: inetmock.git }
            vars:
              docker_repo: code.icb4dc0.de/inetmock
              build_package: ./cmd/inetmock
              push_image: 'true'
