// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: rpc/v1/endpoint.proto

package rpcv1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenerGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints []string `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *ListenerGroup) Reset() {
	*x = ListenerGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerGroup) ProtoMessage() {}

func (x *ListenerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerGroup.ProtoReflect.Descriptor instead.
func (*ListenerGroup) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListenerGroup) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ListAllServingGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAllServingGroupsRequest) Reset() {
	*x = ListAllServingGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllServingGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllServingGroupsRequest) ProtoMessage() {}

func (x *ListAllServingGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllServingGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListAllServingGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{1}
}

type ListAllServingGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*ListenerGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *ListAllServingGroupsResponse) Reset() {
	*x = ListAllServingGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllServingGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllServingGroupsResponse) ProtoMessage() {}

func (x *ListAllServingGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllServingGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListAllServingGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *ListAllServingGroupsResponse) GetGroups() []*ListenerGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ListAllConfiguredGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAllConfiguredGroupsRequest) Reset() {
	*x = ListAllConfiguredGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllConfiguredGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllConfiguredGroupsRequest) ProtoMessage() {}

func (x *ListAllConfiguredGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllConfiguredGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListAllConfiguredGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{3}
}

type ListAllConfiguredGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*ListenerGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *ListAllConfiguredGroupsResponse) Reset() {
	*x = ListAllConfiguredGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllConfiguredGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllConfiguredGroupsResponse) ProtoMessage() {}

func (x *ListAllConfiguredGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllConfiguredGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListAllConfiguredGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllConfiguredGroupsResponse) GetGroups() []*ListenerGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type StartListenerGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *StartListenerGroupRequest) Reset() {
	*x = StartListenerGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartListenerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartListenerGroupRequest) ProtoMessage() {}

func (x *StartListenerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartListenerGroupRequest.ProtoReflect.Descriptor instead.
func (*StartListenerGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *StartListenerGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type StartListenerGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartListenerGroupResponse) Reset() {
	*x = StartListenerGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartListenerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartListenerGroupResponse) ProtoMessage() {}

func (x *StartListenerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartListenerGroupResponse.ProtoReflect.Descriptor instead.
func (*StartListenerGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{6}
}

type StartAllGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartAllGroupsRequest) Reset() {
	*x = StartAllGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartAllGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAllGroupsRequest) ProtoMessage() {}

func (x *StartAllGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAllGroupsRequest.ProtoReflect.Descriptor instead.
func (*StartAllGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{7}
}

type StartAllGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartAllGroupsResponse) Reset() {
	*x = StartAllGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartAllGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAllGroupsResponse) ProtoMessage() {}

func (x *StartAllGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAllGroupsResponse.ProtoReflect.Descriptor instead.
func (*StartAllGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{8}
}

type StopListenerGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *StopListenerGroupRequest) Reset() {
	*x = StopListenerGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopListenerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopListenerGroupRequest) ProtoMessage() {}

func (x *StopListenerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopListenerGroupRequest.ProtoReflect.Descriptor instead.
func (*StopListenerGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *StopListenerGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type StopListenerGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopListenerGroupResponse) Reset() {
	*x = StopListenerGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopListenerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopListenerGroupResponse) ProtoMessage() {}

func (x *StopListenerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopListenerGroupResponse.ProtoReflect.Descriptor instead.
func (*StopListenerGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{10}
}

type StopAllGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopAllGroupsRequest) Reset() {
	*x = StopAllGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAllGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllGroupsRequest) ProtoMessage() {}

func (x *StopAllGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllGroupsRequest.ProtoReflect.Descriptor instead.
func (*StopAllGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{11}
}

type StopAllGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopAllGroupsResponse) Reset() {
	*x = StopAllGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAllGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllGroupsResponse) ProtoMessage() {}

func (x *StopAllGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllGroupsResponse.ProtoReflect.Descriptor instead.
func (*StopAllGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{12}
}

type RestartListenerGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *RestartListenerGroupRequest) Reset() {
	*x = RestartListenerGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartListenerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartListenerGroupRequest) ProtoMessage() {}

func (x *RestartListenerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartListenerGroupRequest.ProtoReflect.Descriptor instead.
func (*RestartListenerGroupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{13}
}

func (x *RestartListenerGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type RestartListenerGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RestartListenerGroupResponse) Reset() {
	*x = RestartListenerGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartListenerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartListenerGroupResponse) ProtoMessage() {}

func (x *RestartListenerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartListenerGroupResponse.ProtoReflect.Descriptor instead.
func (*RestartListenerGroupResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{14}
}

type RestartAllGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RestartAllGroupsRequest) Reset() {
	*x = RestartAllGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartAllGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartAllGroupsRequest) ProtoMessage() {}

func (x *RestartAllGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartAllGroupsRequest.ProtoReflect.Descriptor instead.
func (*RestartAllGroupsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{15}
}

type RestartAllGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RestartAllGroupsResponse) Reset() {
	*x = RestartAllGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_endpoint_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartAllGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartAllGroupsResponse) ProtoMessage() {}

func (x *RestartAllGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_endpoint_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartAllGroupsResponse.ProtoReflect.Descriptor instead.
func (*RestartAllGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_endpoint_proto_rawDescGZIP(), []int{16}
}

var File_rpc_v1_endpoint_proto protoreflect.FileDescriptor

var file_rpc_v1_endpoint_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63,
	0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x41, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x1c, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x65,
	0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x22, 0x20, 0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f,
	0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22,
	0x3a, 0x0a, 0x19, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x18,
	0x53, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x74, 0x6f, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x6c, 0x6c, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15,
	0x53, 0x74, 0x6f, 0x70, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a,
	0x0a, 0x18, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8c, 0x07, 0x0a, 0x1b, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x2c, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e,
	0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x7c, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x2f, 0x2e, 0x69, 0x6e, 0x65,
	0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x69, 0x6e,
	0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a,
	0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x2a, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x26,
	0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63,
	0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x6a, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x29, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0d, 0x53,
	0x74, 0x6f, 0x70, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x25, 0x2e, 0x69,
	0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x14, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x2c, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2d, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x67, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x12, 0x28, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xb3, 0x01, 0x0a, 0x13, 0x63, 0x6f,
	0x6d, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x42, 0x0d, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x48, 0x02, 0x50, 0x01, 0x5a, 0x2d, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x69,
	0x63, 0x62, 0x34, 0x64, 0x63, 0x30, 0x2e, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f,
	0x63, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x70,
	0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x49, 0x52, 0x58, 0xaa, 0x02, 0x0f, 0x49, 0x6e, 0x65, 0x74,
	0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x49, 0x6e,
	0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b,
	0x49, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x49, 0x6e,
	0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x3a, 0x3a, 0x52, 0x70, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_v1_endpoint_proto_rawDescOnce sync.Once
	file_rpc_v1_endpoint_proto_rawDescData = file_rpc_v1_endpoint_proto_rawDesc
)

func file_rpc_v1_endpoint_proto_rawDescGZIP() []byte {
	file_rpc_v1_endpoint_proto_rawDescOnce.Do(func() {
		file_rpc_v1_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_v1_endpoint_proto_rawDescData)
	})
	return file_rpc_v1_endpoint_proto_rawDescData
}

var file_rpc_v1_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_rpc_v1_endpoint_proto_goTypes = []interface{}{
	(*ListenerGroup)(nil),                   // 0: inetmock.rpc.v1.ListenerGroup
	(*ListAllServingGroupsRequest)(nil),     // 1: inetmock.rpc.v1.ListAllServingGroupsRequest
	(*ListAllServingGroupsResponse)(nil),    // 2: inetmock.rpc.v1.ListAllServingGroupsResponse
	(*ListAllConfiguredGroupsRequest)(nil),  // 3: inetmock.rpc.v1.ListAllConfiguredGroupsRequest
	(*ListAllConfiguredGroupsResponse)(nil), // 4: inetmock.rpc.v1.ListAllConfiguredGroupsResponse
	(*StartListenerGroupRequest)(nil),       // 5: inetmock.rpc.v1.StartListenerGroupRequest
	(*StartListenerGroupResponse)(nil),      // 6: inetmock.rpc.v1.StartListenerGroupResponse
	(*StartAllGroupsRequest)(nil),           // 7: inetmock.rpc.v1.StartAllGroupsRequest
	(*StartAllGroupsResponse)(nil),          // 8: inetmock.rpc.v1.StartAllGroupsResponse
	(*StopListenerGroupRequest)(nil),        // 9: inetmock.rpc.v1.StopListenerGroupRequest
	(*StopListenerGroupResponse)(nil),       // 10: inetmock.rpc.v1.StopListenerGroupResponse
	(*StopAllGroupsRequest)(nil),            // 11: inetmock.rpc.v1.StopAllGroupsRequest
	(*StopAllGroupsResponse)(nil),           // 12: inetmock.rpc.v1.StopAllGroupsResponse
	(*RestartListenerGroupRequest)(nil),     // 13: inetmock.rpc.v1.RestartListenerGroupRequest
	(*RestartListenerGroupResponse)(nil),    // 14: inetmock.rpc.v1.RestartListenerGroupResponse
	(*RestartAllGroupsRequest)(nil),         // 15: inetmock.rpc.v1.RestartAllGroupsRequest
	(*RestartAllGroupsResponse)(nil),        // 16: inetmock.rpc.v1.RestartAllGroupsResponse
}
var file_rpc_v1_endpoint_proto_depIdxs = []int32{
	0,  // 0: inetmock.rpc.v1.ListAllServingGroupsResponse.groups:type_name -> inetmock.rpc.v1.ListenerGroup
	0,  // 1: inetmock.rpc.v1.ListAllConfiguredGroupsResponse.groups:type_name -> inetmock.rpc.v1.ListenerGroup
	1,  // 2: inetmock.rpc.v1.EndpointOrchestratorService.ListAllServingGroups:input_type -> inetmock.rpc.v1.ListAllServingGroupsRequest
	3,  // 3: inetmock.rpc.v1.EndpointOrchestratorService.ListAllConfiguredGroups:input_type -> inetmock.rpc.v1.ListAllConfiguredGroupsRequest
	5,  // 4: inetmock.rpc.v1.EndpointOrchestratorService.StartListenerGroup:input_type -> inetmock.rpc.v1.StartListenerGroupRequest
	7,  // 5: inetmock.rpc.v1.EndpointOrchestratorService.StartAllGroups:input_type -> inetmock.rpc.v1.StartAllGroupsRequest
	9,  // 6: inetmock.rpc.v1.EndpointOrchestratorService.StopListenerGroup:input_type -> inetmock.rpc.v1.StopListenerGroupRequest
	11, // 7: inetmock.rpc.v1.EndpointOrchestratorService.StopAllGroups:input_type -> inetmock.rpc.v1.StopAllGroupsRequest
	13, // 8: inetmock.rpc.v1.EndpointOrchestratorService.RestartListenerGroup:input_type -> inetmock.rpc.v1.RestartListenerGroupRequest
	15, // 9: inetmock.rpc.v1.EndpointOrchestratorService.RestartAllGroups:input_type -> inetmock.rpc.v1.RestartAllGroupsRequest
	2,  // 10: inetmock.rpc.v1.EndpointOrchestratorService.ListAllServingGroups:output_type -> inetmock.rpc.v1.ListAllServingGroupsResponse
	4,  // 11: inetmock.rpc.v1.EndpointOrchestratorService.ListAllConfiguredGroups:output_type -> inetmock.rpc.v1.ListAllConfiguredGroupsResponse
	6,  // 12: inetmock.rpc.v1.EndpointOrchestratorService.StartListenerGroup:output_type -> inetmock.rpc.v1.StartListenerGroupResponse
	8,  // 13: inetmock.rpc.v1.EndpointOrchestratorService.StartAllGroups:output_type -> inetmock.rpc.v1.StartAllGroupsResponse
	10, // 14: inetmock.rpc.v1.EndpointOrchestratorService.StopListenerGroup:output_type -> inetmock.rpc.v1.StopListenerGroupResponse
	12, // 15: inetmock.rpc.v1.EndpointOrchestratorService.StopAllGroups:output_type -> inetmock.rpc.v1.StopAllGroupsResponse
	14, // 16: inetmock.rpc.v1.EndpointOrchestratorService.RestartListenerGroup:output_type -> inetmock.rpc.v1.RestartListenerGroupResponse
	16, // 17: inetmock.rpc.v1.EndpointOrchestratorService.RestartAllGroups:output_type -> inetmock.rpc.v1.RestartAllGroupsResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_v1_endpoint_proto_init() }
func file_rpc_v1_endpoint_proto_init() {
	if File_rpc_v1_endpoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_v1_endpoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenerGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllServingGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllServingGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllConfiguredGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllConfiguredGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartListenerGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartListenerGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartAllGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartAllGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopListenerGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopListenerGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAllGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAllGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartListenerGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartListenerGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartAllGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_endpoint_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartAllGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_v1_endpoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_endpoint_proto_goTypes,
		DependencyIndexes: file_rpc_v1_endpoint_proto_depIdxs,
		MessageInfos:      file_rpc_v1_endpoint_proto_msgTypes,
	}.Build()
	File_rpc_v1_endpoint_proto = out.File
	file_rpc_v1_endpoint_proto_rawDesc = nil
	file_rpc_v1_endpoint_proto_goTypes = nil
	file_rpc_v1_endpoint_proto_depIdxs = nil
}
