// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: rpc/audit.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	audit "gitlab.com/inetmock/inetmock/pkg/audit"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FileOpenMode int32

const (
	FileOpenMode_TRUNCATE FileOpenMode = 0
	FileOpenMode_APPEND   FileOpenMode = 1
)

// Enum value maps for FileOpenMode.
var (
	FileOpenMode_name = map[int32]string{
		0: "TRUNCATE",
		1: "APPEND",
	}
	FileOpenMode_value = map[string]int32{
		"TRUNCATE": 0,
		"APPEND":   1,
	}
)

func (x FileOpenMode) Enum() *FileOpenMode {
	p := new(FileOpenMode)
	*p = x
	return p
}

func (x FileOpenMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileOpenMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_audit_proto_enumTypes[0].Descriptor()
}

func (FileOpenMode) Type() protoreflect.EnumType {
	return &file_rpc_audit_proto_enumTypes[0]
}

func (x FileOpenMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileOpenMode.Descriptor instead.
func (FileOpenMode) EnumDescriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{0}
}

type WatchEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WatcherName string `protobuf:"bytes,1,opt,name=watcherName,proto3" json:"watcherName,omitempty"`
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_audit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_audit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{0}
}

func (x *WatchEventsRequest) GetWatcherName() string {
	if x != nil {
		return x.WatcherName
	}
	return ""
}

type RegisterFileSinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetPath  string       `protobuf:"bytes,1,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
	OpenMode    FileOpenMode `protobuf:"varint,2,opt,name=openMode,proto3,enum=inetmock.rpc.FileOpenMode" json:"openMode,omitempty"`
	Permissions uint32       `protobuf:"varint,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *RegisterFileSinkRequest) Reset() {
	*x = RegisterFileSinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_audit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterFileSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileSinkRequest) ProtoMessage() {}

func (x *RegisterFileSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_audit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileSinkRequest.ProtoReflect.Descriptor instead.
func (*RegisterFileSinkRequest) Descriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterFileSinkRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *RegisterFileSinkRequest) GetOpenMode() FileOpenMode {
	if x != nil {
		return x.OpenMode
	}
	return FileOpenMode_TRUNCATE
}

func (x *RegisterFileSinkRequest) GetPermissions() uint32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

type RegisterFileSinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterFileSinkResponse) Reset() {
	*x = RegisterFileSinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_audit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterFileSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileSinkResponse) ProtoMessage() {}

func (x *RegisterFileSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_audit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileSinkResponse.ProtoReflect.Descriptor instead.
func (*RegisterFileSinkResponse) Descriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{2}
}

type RemoveFileSinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetPath string `protobuf:"bytes,1,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
}

func (x *RemoveFileSinkRequest) Reset() {
	*x = RemoveFileSinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_audit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFileSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileSinkRequest) ProtoMessage() {}

func (x *RemoveFileSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_audit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileSinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileSinkRequest) Descriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFileSinkRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type RemoveFileSinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SinkGotRemoved bool `protobuf:"varint,1,opt,name=SinkGotRemoved,proto3" json:"SinkGotRemoved,omitempty"`
}

func (x *RemoveFileSinkResponse) Reset() {
	*x = RemoveFileSinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_audit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFileSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileSinkResponse) ProtoMessage() {}

func (x *RemoveFileSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_audit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileSinkResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileSinkResponse) Descriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFileSinkResponse) GetSinkGotRemoved() bool {
	if x != nil {
		return x.SinkGotRemoved
	}
	return false
}

type ListSinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSinksRequest) Reset() {
	*x = ListSinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_audit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSinksRequest) ProtoMessage() {}

func (x *ListSinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_audit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSinksRequest.ProtoReflect.Descriptor instead.
func (*ListSinksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{5}
}

type ListSinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sinks []string `protobuf:"bytes,1,rep,name=sinks,proto3" json:"sinks,omitempty"`
}

func (x *ListSinksResponse) Reset() {
	*x = ListSinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_audit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSinksResponse) ProtoMessage() {}

func (x *ListSinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_audit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSinksResponse.ProtoReflect.Descriptor instead.
func (*ListSinksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_audit_proto_rawDescGZIP(), []int{6}
}

func (x *ListSinksResponse) GetSinks() []string {
	if x != nil {
		return x.Sinks
	}
	return nil
}

var File_rpc_audit_proto protoreflect.FileDescriptor

var file_rpc_audit_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x1a,
	0x18, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x12, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x93, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x36, 0x0a,
	0x08, 0x6f, 0x70, 0x65, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x6f, 0x70, 0x65,
	0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x40, 0x0a, 0x16,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x6b, 0x47, 0x6f,
	0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e,
	0x53, 0x69, 0x6e, 0x6b, 0x47, 0x6f, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x12,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x29, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x69, 0x6e, 0x6b, 0x73, 0x2a, 0x28, 0x0a,
	0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x54, 0x52, 0x55, 0x4e, 0x43, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x50, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x32, 0xe5, 0x02, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69,
	0x74, 0x12, 0x4e, 0x0a, 0x0b, 0x57, 0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x20, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x30,
	0x01, 0x12, 0x61, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x69, 0x6e, 0x6b, 0x12, 0x25, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x69,
	0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x12, 0x23, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63,
	0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x6e,
	0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4c, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1e,
	0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x6a, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x62, 0x61,
	0x65, 0x7a, 0x39, 0x30, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70,
	0x63, 0x42, 0x0a, 0x41, 0x75, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x24, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x65, 0x74,
	0x6d, 0x6f, 0x63, 0x6b, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x13, 0x49, 0x4e, 0x65, 0x74, 0x4d, 0x6f, 0x63, 0x6b,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_audit_proto_rawDescOnce sync.Once
	file_rpc_audit_proto_rawDescData = file_rpc_audit_proto_rawDesc
)

func file_rpc_audit_proto_rawDescGZIP() []byte {
	file_rpc_audit_proto_rawDescOnce.Do(func() {
		file_rpc_audit_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_audit_proto_rawDescData)
	})
	return file_rpc_audit_proto_rawDescData
}

var file_rpc_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_audit_proto_goTypes = []interface{}{
	(FileOpenMode)(0),                // 0: inetmock.rpc.FileOpenMode
	(*WatchEventsRequest)(nil),       // 1: inetmock.rpc.WatchEventsRequest
	(*RegisterFileSinkRequest)(nil),  // 2: inetmock.rpc.RegisterFileSinkRequest
	(*RegisterFileSinkResponse)(nil), // 3: inetmock.rpc.RegisterFileSinkResponse
	(*RemoveFileSinkRequest)(nil),    // 4: inetmock.rpc.RemoveFileSinkRequest
	(*RemoveFileSinkResponse)(nil),   // 5: inetmock.rpc.RemoveFileSinkResponse
	(*ListSinksRequest)(nil),         // 6: inetmock.rpc.ListSinksRequest
	(*ListSinksResponse)(nil),        // 7: inetmock.rpc.ListSinksResponse
	(*audit.EventEntity)(nil),        // 8: inetmock.audit.EventEntity
}
var file_rpc_audit_proto_depIdxs = []int32{
	0, // 0: inetmock.rpc.RegisterFileSinkRequest.openMode:type_name -> inetmock.rpc.FileOpenMode
	1, // 1: inetmock.rpc.Audit.WatchEvents:input_type -> inetmock.rpc.WatchEventsRequest
	2, // 2: inetmock.rpc.Audit.RegisterFileSink:input_type -> inetmock.rpc.RegisterFileSinkRequest
	4, // 3: inetmock.rpc.Audit.RemoveFileSink:input_type -> inetmock.rpc.RemoveFileSinkRequest
	6, // 4: inetmock.rpc.Audit.ListSinks:input_type -> inetmock.rpc.ListSinksRequest
	8, // 5: inetmock.rpc.Audit.WatchEvents:output_type -> inetmock.audit.EventEntity
	3, // 6: inetmock.rpc.Audit.RegisterFileSink:output_type -> inetmock.rpc.RegisterFileSinkResponse
	5, // 7: inetmock.rpc.Audit.RemoveFileSink:output_type -> inetmock.rpc.RemoveFileSinkResponse
	7, // 8: inetmock.rpc.Audit.ListSinks:output_type -> inetmock.rpc.ListSinksResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_audit_proto_init() }
func file_rpc_audit_proto_init() {
	if File_rpc_audit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_audit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_audit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterFileSinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_audit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterFileSinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_audit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFileSinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_audit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFileSinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_audit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_audit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_audit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_audit_proto_goTypes,
		DependencyIndexes: file_rpc_audit_proto_depIdxs,
		EnumInfos:         file_rpc_audit_proto_enumTypes,
		MessageInfos:      file_rpc_audit_proto_msgTypes,
	}.Build()
	File_rpc_audit_proto = out.File
	file_rpc_audit_proto_rawDesc = nil
	file_rpc_audit_proto_goTypes = nil
	file_rpc_audit_proto_depIdxs = nil
}
