// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: rpc/pcap.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListAvailableDevicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAvailableDevicesRequest) Reset() {
	*x = ListAvailableDevicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAvailableDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableDevicesRequest) ProtoMessage() {}

func (x *ListAvailableDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableDevicesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{0}
}

type ListAvailableDevicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailableDevices []*ListAvailableDevicesResponse_PCAPDevice `protobuf:"bytes,1,rep,name=availableDevices,proto3" json:"availableDevices,omitempty"`
}

func (x *ListAvailableDevicesResponse) Reset() {
	*x = ListAvailableDevicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAvailableDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableDevicesResponse) ProtoMessage() {}

func (x *ListAvailableDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableDevicesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{1}
}

func (x *ListAvailableDevicesResponse) GetAvailableDevices() []*ListAvailableDevicesResponse_PCAPDevice {
	if x != nil {
		return x.AvailableDevices
	}
	return nil
}

type ListRecordingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRecordingsRequest) Reset() {
	*x = ListRecordingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordingsRequest) ProtoMessage() {}

func (x *ListRecordingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordingsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordingsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{2}
}

type ListRecordingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscriptions map[string]*ListRecordingsResponse_ConsumerList `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListRecordingsResponse) Reset() {
	*x = ListRecordingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordingsResponse) ProtoMessage() {}

func (x *ListRecordingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordingsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordingsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{3}
}

func (x *ListRecordingsResponse) GetSubscriptions() map[string]*ListRecordingsResponse_ConsumerList {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type RegisterPCAPFileRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device     string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	TargetPath string `protobuf:"bytes,2,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
}

func (x *RegisterPCAPFileRecordRequest) Reset() {
	*x = RegisterPCAPFileRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPCAPFileRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPCAPFileRecordRequest) ProtoMessage() {}

func (x *RegisterPCAPFileRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPCAPFileRecordRequest.ProtoReflect.Descriptor instead.
func (*RegisterPCAPFileRecordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterPCAPFileRecordRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *RegisterPCAPFileRecordRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type RegisterPCAPFileRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResolvedPath string `protobuf:"bytes,1,opt,name=resolvedPath,proto3" json:"resolvedPath,omitempty"`
}

func (x *RegisterPCAPFileRecordResponse) Reset() {
	*x = RegisterPCAPFileRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPCAPFileRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPCAPFileRecordResponse) ProtoMessage() {}

func (x *RegisterPCAPFileRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPCAPFileRecordResponse.ProtoReflect.Descriptor instead.
func (*RegisterPCAPFileRecordResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterPCAPFileRecordResponse) GetResolvedPath() string {
	if x != nil {
		return x.ResolvedPath
	}
	return ""
}

type RemovePCAPFileRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device     string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	TargetPath string `protobuf:"bytes,2,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
}

func (x *RemovePCAPFileRecordRequest) Reset() {
	*x = RemovePCAPFileRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePCAPFileRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePCAPFileRecordRequest) ProtoMessage() {}

func (x *RemovePCAPFileRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePCAPFileRecordRequest.ProtoReflect.Descriptor instead.
func (*RemovePCAPFileRecordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePCAPFileRecordRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *RemovePCAPFileRecordRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type RemovePCAPFileRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Removed bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *RemovePCAPFileRecordResponse) Reset() {
	*x = RemovePCAPFileRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePCAPFileRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePCAPFileRecordResponse) ProtoMessage() {}

func (x *RemovePCAPFileRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePCAPFileRecordResponse.ProtoReflect.Descriptor instead.
func (*RemovePCAPFileRecordResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{7}
}

func (x *RemovePCAPFileRecordResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListAvailableDevicesResponse_PCAPDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addresses [][]byte `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *ListAvailableDevicesResponse_PCAPDevice) Reset() {
	*x = ListAvailableDevicesResponse_PCAPDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAvailableDevicesResponse_PCAPDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableDevicesResponse_PCAPDevice) ProtoMessage() {}

func (x *ListAvailableDevicesResponse_PCAPDevice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableDevicesResponse_PCAPDevice.ProtoReflect.Descriptor instead.
func (*ListAvailableDevicesResponse_PCAPDevice) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListAvailableDevicesResponse_PCAPDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListAvailableDevicesResponse_PCAPDevice) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type ListRecordingsResponse_ConsumerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consumers []string `protobuf:"bytes,1,rep,name=consumers,proto3" json:"consumers,omitempty"`
}

func (x *ListRecordingsResponse_ConsumerList) Reset() {
	*x = ListRecordingsResponse_ConsumerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pcap_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecordingsResponse_ConsumerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordingsResponse_ConsumerList) ProtoMessage() {}

func (x *ListRecordingsResponse_ConsumerList) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pcap_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordingsResponse_ConsumerList.ProtoReflect.Descriptor instead.
func (*ListRecordingsResponse_ConsumerList) Descriptor() ([]byte, []int) {
	return file_rpc_pcap_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListRecordingsResponse_ConsumerList) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

var File_rpc_pcap_proto protoreflect.FileDescriptor

var file_rpc_pcap_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x63, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x22, 0x1d,
	0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc1, 0x01,
	0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61,
	0x0a, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d,
	0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x43, 0x41, 0x50, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x1a, 0x3e, 0x0a, 0x0a, 0x50, 0x43, 0x41, 0x50, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9a, 0x02, 0x0a, 0x16, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x69,
	0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x2c, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x73, 0x1a, 0x73, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x47, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x69, 0x6e, 0x65, 0x74,
	0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x57, 0x0a, 0x1d, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x50, 0x43, 0x41, 0x50, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x22, 0x44, 0x0a, 0x1e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x43, 0x41, 0x50,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x22, 0x55, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x50, 0x43, 0x41, 0x50, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x38, 0x0a,
	0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x43, 0x41, 0x50, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x32, 0xb6, 0x03, 0x0a, 0x04, 0x50, 0x43, 0x41, 0x50,
	0x12, 0x6d, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x29, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d,
	0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5b, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x23, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63,
	0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x16,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x43, 0x41, 0x50, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x2b, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63,
	0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x43,
	0x41, 0x50, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x43, 0x41, 0x50, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6d, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x43, 0x41, 0x50, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x29, 0x2e, 0x69, 0x6e, 0x65, 0x74,
	0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x43, 0x41, 0x50, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x43, 0x41, 0x50, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x6a, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x62,
	0x61, 0x65, 0x7a, 0x39, 0x30, 0x2e, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2e, 0x72,
	0x70, 0x63, 0x42, 0x0a, 0x41, 0x75, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x65,
	0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2f, 0x69, 0x6e, 0x65, 0x74, 0x6d, 0x6f, 0x63, 0x6b, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0xaa, 0x02, 0x13, 0x49, 0x4e, 0x65, 0x74, 0x4d, 0x6f, 0x63,
	0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_pcap_proto_rawDescOnce sync.Once
	file_rpc_pcap_proto_rawDescData = file_rpc_pcap_proto_rawDesc
)

func file_rpc_pcap_proto_rawDescGZIP() []byte {
	file_rpc_pcap_proto_rawDescOnce.Do(func() {
		file_rpc_pcap_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_pcap_proto_rawDescData)
	})
	return file_rpc_pcap_proto_rawDescData
}

var file_rpc_pcap_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_pcap_proto_goTypes = []interface{}{
	(*ListAvailableDevicesRequest)(nil),             // 0: inetmock.rpc.ListAvailableDevicesRequest
	(*ListAvailableDevicesResponse)(nil),            // 1: inetmock.rpc.ListAvailableDevicesResponse
	(*ListRecordingsRequest)(nil),                   // 2: inetmock.rpc.ListRecordingsRequest
	(*ListRecordingsResponse)(nil),                  // 3: inetmock.rpc.ListRecordingsResponse
	(*RegisterPCAPFileRecordRequest)(nil),           // 4: inetmock.rpc.RegisterPCAPFileRecordRequest
	(*RegisterPCAPFileRecordResponse)(nil),          // 5: inetmock.rpc.RegisterPCAPFileRecordResponse
	(*RemovePCAPFileRecordRequest)(nil),             // 6: inetmock.rpc.RemovePCAPFileRecordRequest
	(*RemovePCAPFileRecordResponse)(nil),            // 7: inetmock.rpc.RemovePCAPFileRecordResponse
	(*ListAvailableDevicesResponse_PCAPDevice)(nil), // 8: inetmock.rpc.ListAvailableDevicesResponse.PCAPDevice
	(*ListRecordingsResponse_ConsumerList)(nil),     // 9: inetmock.rpc.ListRecordingsResponse.ConsumerList
	nil, // 10: inetmock.rpc.ListRecordingsResponse.SubscriptionsEntry
}
var file_rpc_pcap_proto_depIdxs = []int32{
	8,  // 0: inetmock.rpc.ListAvailableDevicesResponse.availableDevices:type_name -> inetmock.rpc.ListAvailableDevicesResponse.PCAPDevice
	10, // 1: inetmock.rpc.ListRecordingsResponse.subscriptions:type_name -> inetmock.rpc.ListRecordingsResponse.SubscriptionsEntry
	9,  // 2: inetmock.rpc.ListRecordingsResponse.SubscriptionsEntry.value:type_name -> inetmock.rpc.ListRecordingsResponse.ConsumerList
	0,  // 3: inetmock.rpc.PCAP.ListAvailableDevices:input_type -> inetmock.rpc.ListAvailableDevicesRequest
	2,  // 4: inetmock.rpc.PCAP.ListRecordings:input_type -> inetmock.rpc.ListRecordingsRequest
	4,  // 5: inetmock.rpc.PCAP.RegisterPCAPFileRecord:input_type -> inetmock.rpc.RegisterPCAPFileRecordRequest
	6,  // 6: inetmock.rpc.PCAP.RemovePCAPFileRecord:input_type -> inetmock.rpc.RemovePCAPFileRecordRequest
	1,  // 7: inetmock.rpc.PCAP.ListAvailableDevices:output_type -> inetmock.rpc.ListAvailableDevicesResponse
	3,  // 8: inetmock.rpc.PCAP.ListRecordings:output_type -> inetmock.rpc.ListRecordingsResponse
	5,  // 9: inetmock.rpc.PCAP.RegisterPCAPFileRecord:output_type -> inetmock.rpc.RegisterPCAPFileRecordResponse
	7,  // 10: inetmock.rpc.PCAP.RemovePCAPFileRecord:output_type -> inetmock.rpc.RemovePCAPFileRecordResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_pcap_proto_init() }
func file_rpc_pcap_proto_init() {
	if File_rpc_pcap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_pcap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAvailableDevicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAvailableDevicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecordingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecordingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPCAPFileRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPCAPFileRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePCAPFileRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePCAPFileRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAvailableDevicesResponse_PCAPDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pcap_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecordingsResponse_ConsumerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_pcap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_pcap_proto_goTypes,
		DependencyIndexes: file_rpc_pcap_proto_depIdxs,
		MessageInfos:      file_rpc_pcap_proto_msgTypes,
	}.Build()
	File_rpc_pcap_proto = out.File
	file_rpc_pcap_proto_rawDesc = nil
	file_rpc_pcap_proto_goTypes = nil
	file_rpc_pcap_proto_depIdxs = nil
}
