name: Go

on: [ push, pull_request ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
        id: go

      - name: Install Protoc
        uses: arduino/setup-protoc@master
        with:
          version: '3.x'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install mockgen
        run: go get -u github.com/golang/mock/mockgen@latest

      - name: Install go-enuum
        run: go get -u github.com/abice/go-enum

      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Build & test
        run: make

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}